name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
    - name: Install nanoc
      run: gem install nanoc
    - name: Build site
      run: |
        cd site
        nanoc
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: site/output
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4